### ISSUE TITLE
Make talks table into bulleted list?!

### ISSUE THREAD

**Issue by isabelcosta** [isabelcosta/fourth-personal-website#13]

**Comment by Shashwati-tidke** [comment]
@isabelcosta  can work on this issue?

**Comment by isabelcosta** [comment]
@Shashwati-tidke thank you for your interest in improving my personal website 🤗 
I don't have a clear picture of how the talks table would look like as a bulleted list 🤔  
Feel free to send a PR if you want :)

**Comment by Shashwati-tidke** [comment]
Ok .Cool :)
